name: smritim_app
description: Smritim mobile application
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_svg: ^2.0.10
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  open_file: ^3.3.2
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/smriti-m.png"
  adaptive_icon_background: "#F1F5FF"
  adaptive_icon_foreground: "assets/logo/smriti-m.png"
