
name: smritim_app
description: Smritim mobile application
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_svg: ^2.0.10
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
